#!/bin/bash
#
# build_uboot.sh - Build U-Boot for embedded targets
#
# AUTO-GENERATED: This script was generated by AI. Verify before use.
#
# This script automates the U-Boot build process for various embedded boards.
# Primary target: BeagleBone Black Rev. C (AM335x)
#
# It handles downloading, configuring, and building U-Boot with proper
# cross-compilation settings. For BeagleBone Black, this generates both
# MLO (SPL) and u-boot.img files.
#
# Usage: ./build_uboot.sh <target>
# Targets: bbb (primary), rpi3, rpi4, imx6, stm32mp1
#
# Example: ./build_uboot.sh bbb
#

set -e  # Exit on error
set -u  # Error on undefined variables

#==============================================================================
# Configuration
#==============================================================================

UBOOT_VERSION="${UBOOT_VERSION:-v2024.01}"
UBOOT_REPO="https://source.denx.de/u-boot/u-boot.git"
WORK_DIR="${WORK_DIR:-$(pwd)/uboot_build}"
OUTPUT_DIR="${OUTPUT_DIR:-$(pwd)/output}"

# Target configurations (BeagleBone Black is primary)
declare -A UBOOT_DEFCONFIG=(
    ["bbb"]="am335x_evm_defconfig"           # Primary target
    ["rpi3"]="rpi_3_defconfig"
    ["rpi3_32"]="rpi_3_32b_defconfig"
    ["rpi4"]="rpi_4_defconfig"
    ["rpi4_32"]="rpi_4_32b_defconfig"
    ["imx6"]="mx6sabresd_defconfig"
    ["stm32mp1"]="stm32mp15_basic_defconfig"
)

declare -A CROSS_COMPILER=(
    ["bbb"]="arm-linux-gnueabihf-"           # AM335x is ARM32
    ["rpi3"]="aarch64-linux-gnu-"
    ["rpi3_32"]="arm-linux-gnueabihf-"
    ["rpi4"]="aarch64-linux-gnu-"
    ["rpi4_32"]="arm-linux-gnueabihf-"
    ["imx6"]="arm-linux-gnueabihf-"
    ["stm32mp1"]="arm-linux-gnueabihf-"
)

declare -A TARGET_ARCH=(
    ["bbb"]="arm"                            # AM335x Cortex-A8
    ["rpi3"]="arm64"
    ["rpi3_32"]="arm"
    ["rpi4"]="arm64"
    ["rpi4_32"]="arm"
    ["imx6"]="arm"
    ["stm32mp1"]="arm"
)

#==============================================================================
# Functions
#==============================================================================

print_usage() {
    echo "Usage: $0 <target> [options]"
    echo ""
    echo "Targets:"
    echo "  bbb       - BeagleBone Black Rev. C (PRIMARY - generates MLO + u-boot.img)"
    echo "  rpi3      - Raspberry Pi 3 (64-bit)"
    echo "  rpi3_32   - Raspberry Pi 3 (32-bit)"
    echo "  rpi4      - Raspberry Pi 4 (64-bit)"
    echo "  rpi4_32   - Raspberry Pi 4 (32-bit)"
    echo "  imx6      - i.MX6 SABRE SD"
    echo "  stm32mp1  - STM32MP157"
    echo ""
    echo "Options:"
    echo "  --clean       Clean build directory before building"
    echo "  --menuconfig  Open menuconfig after applying defconfig"
    echo "  --version VER Specify U-Boot version (default: $UBOOT_VERSION)"
    echo ""
    echo "Environment variables:"
    echo "  UBOOT_VERSION - U-Boot version to build"
    echo "  WORK_DIR      - Build directory"
    echo "  OUTPUT_DIR    - Output directory for binaries"
    echo ""
    echo "Examples:"
    echo "  $0 rpi3                 # Build for Raspberry Pi 3"
    echo "  $0 bbb --menuconfig     # Build for BBB with menuconfig"
    echo "  $0 rpi4 --clean         # Clean build for RPi 4"
}

log_info() {
    echo "[INFO] $1"
}

log_error() {
    echo "[ERROR] $1" >&2
}

check_dependencies() {
    log_info "Checking dependencies..."
    
    local deps=("git" "make" "gcc" "bison" "flex")
    local missing=()
    
    for dep in "${deps[@]}"; do
        if ! command -v "$dep" &> /dev/null; then
            missing+=("$dep")
        fi
    done
    
    # Check cross-compiler
    local cc="${CROSS_COMPILER[$TARGET]}"
    if ! command -v "${cc}gcc" &> /dev/null; then
        log_error "Cross-compiler not found: ${cc}gcc"
        log_error "Install with: sudo apt-get install gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu"
        exit 1
    fi
    
    if [ ${#missing[@]} -ne 0 ]; then
        log_error "Missing dependencies: ${missing[*]}"
        log_error "Install with: sudo apt-get install ${missing[*]}"
        exit 1
    fi
    
    log_info "All dependencies satisfied"
}

fetch_uboot() {
    log_info "Fetching U-Boot source..."
    
    mkdir -p "$WORK_DIR"
    cd "$WORK_DIR"
    
    if [ -d "u-boot" ]; then
        log_info "U-Boot source already exists, updating..."
        cd u-boot
        git fetch --tags
    else
        log_info "Cloning U-Boot repository..."
        git clone --depth 1 --branch "$UBOOT_VERSION" "$UBOOT_REPO"
        cd u-boot
    fi
    
    # Checkout specific version
    git checkout "$UBOOT_VERSION" 2>/dev/null || git checkout -b "build-$UBOOT_VERSION" "$UBOOT_VERSION"
    
    log_info "U-Boot source ready: $(git describe --tags)"
}

configure_uboot() {
    log_info "Configuring U-Boot for $TARGET..."
    
    cd "$WORK_DIR/u-boot"
    
    local defconfig="${UBOOT_DEFCONFIG[$TARGET]}"
    local arch="${TARGET_ARCH[$TARGET]}"
    local cross="${CROSS_COMPILER[$TARGET]}"
    
    export ARCH="$arch"
    export CROSS_COMPILE="$cross"
    
    log_info "Using defconfig: $defconfig"
    log_info "Architecture: $arch"
    log_info "Cross-compiler: $cross"
    
    make "$defconfig"
    
    if [ "$DO_MENUCONFIG" = true ]; then
        log_info "Opening menuconfig..."
        make menuconfig
    fi
}

build_uboot() {
    log_info "Building U-Boot..."
    
    cd "$WORK_DIR/u-boot"
    
    local arch="${TARGET_ARCH[$TARGET]}"
    local cross="${CROSS_COMPILER[$TARGET]}"
    
    export ARCH="$arch"
    export CROSS_COMPILE="$cross"
    
    make -j"$(nproc)"
    
    log_info "Build completed successfully"
}

install_uboot() {
    log_info "Copying output files..."
    
    mkdir -p "$OUTPUT_DIR/$TARGET"
    cd "$WORK_DIR/u-boot"
    
    # Copy main U-Boot binary
    if [ -f "u-boot.bin" ]; then
        cp u-boot.bin "$OUTPUT_DIR/$TARGET/"
        log_info "Copied: u-boot.bin"
    fi
    
    if [ -f "u-boot.img" ]; then
        cp u-boot.img "$OUTPUT_DIR/$TARGET/"
        log_info "Copied: u-boot.img"
    fi
    
    # Copy SPL if present
    if [ -f "spl/u-boot-spl.bin" ]; then
        cp spl/u-boot-spl.bin "$OUTPUT_DIR/$TARGET/"
        log_info "Copied: u-boot-spl.bin"
    fi
    
    # Copy MLO for AM335x
    if [ -f "MLO" ]; then
        cp MLO "$OUTPUT_DIR/$TARGET/"
        log_info "Copied: MLO"
    fi
    
    # Copy device tree if present
    for dtb in *.dtb arch/arm/dts/*.dtb; do
        if [ -f "$dtb" ]; then
            cp "$dtb" "$OUTPUT_DIR/$TARGET/" 2>/dev/null || true
        fi
    done
    
    log_info ""
    log_info "Output files in: $OUTPUT_DIR/$TARGET/"
    ls -lh "$OUTPUT_DIR/$TARGET/"
}

print_deploy_instructions() {
    echo ""
    echo "=============================================="
    echo "  Deployment Instructions for $TARGET"
    echo "=============================================="
    echo ""
    
    case "$TARGET" in
        rpi3|rpi3_32|rpi4|rpi4_32)
            echo "For Raspberry Pi:"
            echo "  1. Mount boot partition: sudo mount /dev/sdX1 /mnt"
            echo "  2. Copy U-Boot: sudo cp $OUTPUT_DIR/$TARGET/u-boot.bin /mnt/"
            echo "  3. Edit config.txt, add: kernel=u-boot.bin"
            echo "  4. Unmount: sudo umount /mnt"
            ;;
        bbb)
            echo "For BeagleBone Black:"
            echo "  1. Mount boot partition: sudo mount /dev/sdX1 /mnt"
            echo "  2. Copy MLO: sudo cp $OUTPUT_DIR/$TARGET/MLO /mnt/"
            echo "  3. Copy U-Boot: sudo cp $OUTPUT_DIR/$TARGET/u-boot.img /mnt/"
            echo "  4. Unmount: sudo umount /mnt"
            ;;
        imx6)
            echo "For i.MX6 SABRE:"
            echo "  1. Write SPL: sudo dd if=$OUTPUT_DIR/$TARGET/SPL of=/dev/sdX bs=1k seek=1"
            echo "  2. Write U-Boot: sudo dd if=$OUTPUT_DIR/$TARGET/u-boot.img of=/dev/sdX bs=1k seek=69"
            ;;
        stm32mp1)
            echo "For STM32MP1:"
            echo "  1. Use STM32CubeProgrammer to flash U-Boot"
            echo "  2. Or write to SD card boot partitions"
            ;;
    esac
    
    echo ""
    echo "Remember to:"
    echo "  - Backup existing bootloader first!"
    echo "  - Have serial console connected"
    echo "  - Know recovery procedure"
    echo ""
}

clean_build() {
    log_info "Cleaning build directory..."
    
    if [ -d "$WORK_DIR/u-boot" ]; then
        cd "$WORK_DIR/u-boot"
        make distclean
    fi
    
    log_info "Clean completed"
}

#==============================================================================
# Main Script
#==============================================================================

# Parse arguments
TARGET=""
DO_CLEAN=false
DO_MENUCONFIG=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --clean)
            DO_CLEAN=true
            shift
            ;;
        --menuconfig)
            DO_MENUCONFIG=true
            shift
            ;;
        --version)
            UBOOT_VERSION="$2"
            shift 2
            ;;
        -h|--help)
            print_usage
            exit 0
            ;;
        *)
            if [ -z "$TARGET" ]; then
                TARGET="$1"
            else
                log_error "Unknown argument: $1"
                print_usage
                exit 1
            fi
            shift
            ;;
    esac
done

# Validate target
if [ -z "$TARGET" ]; then
    log_error "No target specified"
    print_usage
    exit 1
fi

if [ -z "${UBOOT_DEFCONFIG[$TARGET]:-}" ]; then
    log_error "Unknown target: $TARGET"
    print_usage
    exit 1
fi

# Run build steps
echo ""
echo "=============================================="
echo "  U-Boot Build Script"
echo "=============================================="
echo "  Target:       $TARGET"
echo "  Version:      $UBOOT_VERSION"
echo "  Defconfig:    ${UBOOT_DEFCONFIG[$TARGET]}"
echo "  Cross-compiler: ${CROSS_COMPILER[$TARGET]}"
echo "  Work directory: $WORK_DIR"
echo "  Output directory: $OUTPUT_DIR"
echo "=============================================="
echo ""

check_dependencies

if [ "$DO_CLEAN" = true ]; then
    clean_build
fi

fetch_uboot
configure_uboot
build_uboot
install_uboot
print_deploy_instructions

log_info "Done!"
