#!/bin/bash
#===============================================================================
# build_all.sh - Master Build Orchestration Script for Embedded Linux Labs
#===============================================================================
# AUTO-GENERATED: This script was generated by AI. Verify before use.
#
# This script orchestrates the build of all Embedded Linux components:
# - U-Boot bootloader (including SPL/MLO for BeagleBone Black)
# - Linux kernel
# - Device tree blobs
# - Initramfs
#
# PRIMARY TARGET: BeagleBone Black Rev. C (AM335x)
#
# Usage: ./build_all.sh <target>
#   Targets: bbb (primary), rpi3, rpi4, imx6, stm32mp1
#
# Example: ./build_all.sh bbb
#
# Author: Embedded Linux Labs (AI-Generated)
# License: MIT
#===============================================================================

set -e  # Exit on any error
set -u  # Treat unset variables as errors

#-------------------------------------------------------------------------------
# Configuration
#-------------------------------------------------------------------------------

# Script directory (absolute path)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source directories
UBOOT_DIR="${SCRIPT_DIR}/sources/u-boot"
KERNEL_DIR="${SCRIPT_DIR}/sources/linux"
BUSYBOX_DIR="${SCRIPT_DIR}/sources/busybox"

# Output directory
OUTPUT_DIR="${SCRIPT_DIR}/output"

# Number of parallel jobs for make
JOBS=$(nproc)

# Supported targets and their configurations (BBB is primary)
declare -A TARGET_ARCH=(
    ["bbb"]="arm"                   # Primary target - BeagleBone Black
    ["rpi3"]="arm64"
    ["rpi4"]="arm64"
    ["imx6"]="arm"
    ["stm32mp1"]="arm"
)

declare -A TARGET_CROSS_COMPILE=(
    ["bbb"]="arm-linux-gnueabihf-"  # AM335x Cortex-A8
    ["rpi3"]="aarch64-linux-gnu-"
    ["rpi4"]="aarch64-linux-gnu-"
    ["imx6"]="arm-linux-gnueabihf-"
    ["stm32mp1"]="arm-linux-gnueabihf-"
)

declare -A UBOOT_DEFCONFIG=(
    ["bbb"]="am335x_evm_defconfig"  # Generates MLO + u-boot.img
    ["rpi3"]="rpi_3_defconfig"
    ["rpi4"]="rpi_4_defconfig"
    ["imx6"]="mx6sabresd_defconfig"
    ["stm32mp1"]="stm32mp15_basic_defconfig"
)

declare -A KERNEL_DEFCONFIG=(
    ["bbb"]="omap2plus_defconfig"   # TI OMAP/AM335x
    ["rpi3"]="bcm2711_defconfig"
    ["rpi4"]="bcm2711_defconfig"
    ["imx6"]="imx_v6_v7_defconfig"
    ["stm32mp1"]="multi_v7_defconfig"
)

declare -A KERNEL_IMAGE=(
    ["bbb"]="zImage"                # AM335x uses zImage
    ["rpi3"]="Image"
    ["rpi4"]="Image"
    ["imx6"]="zImage"
    ["stm32mp1"]="zImage"
)

declare -A KERNEL_DTB=(
    ["bbb"]="am335x-boneblack.dtb"  # BeagleBone Black device tree
    ["rpi3"]="broadcom/bcm2710-rpi-3-b.dtb"
    ["rpi4"]="broadcom/bcm2711-rpi-4-b.dtb"
    ["imx6"]="imx6q-sabresd.dtb"
    ["stm32mp1"]="stm32mp157c-dk2.dtb"
)

#-------------------------------------------------------------------------------
# Color Output Functions
#-------------------------------------------------------------------------------

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

#-------------------------------------------------------------------------------
# Helper Functions
#-------------------------------------------------------------------------------

print_banner() {
    echo ""
    echo "==============================================================================="
    echo "  Embedded Linux Labs - Master Build Script"
    echo "==============================================================================="
    echo ""
}

print_usage() {
    echo "Usage: $0 <target>"
    echo ""
    echo "Supported targets:"
    echo "  rpi3     - Raspberry Pi 3B/3B+ (64-bit)"
    echo "  rpi4     - Raspberry Pi 4 (64-bit)"
    echo "  bbb      - BeagleBone Black"
    echo "  imx6     - i.MX6 Sabre SD"
    echo "  stm32mp1 - STM32MP157"
    echo ""
    echo "Example:"
    echo "  $0 rpi3"
    echo ""
}

check_dependencies() {
    log_info "Checking build dependencies..."
    
    local missing_deps=()
    
    # Check for required tools
    local required_tools=(
        "git"
        "make"
        "gcc"
        "flex"
        "bison"
        "dtc"
        "mkimage"
    )
    
    for tool in "${required_tools[@]}"; do
        if ! command -v "$tool" &> /dev/null; then
            missing_deps+=("$tool")
        fi
    done
    
    # Check for cross-compiler
    local cross="${TARGET_CROSS_COMPILE[$TARGET]}gcc"
    if ! command -v "$cross" &> /dev/null; then
        log_warn "Cross-compiler ${cross} not found in PATH"
        log_info "You may need to install it or add it to your PATH"
    fi
    
    if [ ${#missing_deps[@]} -ne 0 ]; then
        log_error "Missing dependencies: ${missing_deps[*]}"
        echo ""
        echo "Install with:"
        echo "  sudo apt-get install git make gcc flex bison device-tree-compiler u-boot-tools"
        exit 1
    fi
    
    log_success "All dependencies found"
}

create_directories() {
    log_info "Creating output directories..."
    
    mkdir -p "${OUTPUT_DIR}/${TARGET}"
    mkdir -p "${OUTPUT_DIR}/${TARGET}/boot"
    mkdir -p "${OUTPUT_DIR}/${TARGET}/rootfs"
    mkdir -p "${SCRIPT_DIR}/sources"
    
    log_success "Directories created"
}

#-------------------------------------------------------------------------------
# Source Acquisition Functions
#-------------------------------------------------------------------------------

fetch_uboot() {
    log_info "Fetching U-Boot source..."
    
    if [ -d "${UBOOT_DIR}" ]; then
        log_info "U-Boot source already exists, updating..."
        cd "${UBOOT_DIR}"
        git fetch origin
        git checkout v2024.01 2>/dev/null || git checkout master
    else
        log_info "Cloning U-Boot repository..."
        git clone --depth 1 --branch v2024.01 \
            https://source.denx.de/u-boot/u-boot.git \
            "${UBOOT_DIR}" 2>/dev/null || \
        git clone --depth 1 \
            https://source.denx.de/u-boot/u-boot.git \
            "${UBOOT_DIR}"
    fi
    
    log_success "U-Boot source ready"
}

fetch_kernel() {
    log_info "Fetching Linux kernel source..."
    
    if [ -d "${KERNEL_DIR}" ]; then
        log_info "Kernel source already exists, updating..."
        cd "${KERNEL_DIR}"
        git fetch origin
    else
        log_info "Cloning Linux kernel repository (this may take a while)..."
        git clone --depth 1 --branch linux-6.6.y \
            https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git \
            "${KERNEL_DIR}" 2>/dev/null || \
        git clone --depth 1 \
            https://github.com/raspberrypi/linux.git \
            "${KERNEL_DIR}"
    fi
    
    log_success "Kernel source ready"
}

fetch_busybox() {
    log_info "Fetching BusyBox source..."
    
    if [ -d "${BUSYBOX_DIR}" ]; then
        log_info "BusyBox source already exists"
    else
        log_info "Cloning BusyBox repository..."
        git clone --depth 1 --branch 1_36_stable \
            https://git.busybox.net/busybox \
            "${BUSYBOX_DIR}" 2>/dev/null || \
        git clone --depth 1 \
            https://git.busybox.net/busybox \
            "${BUSYBOX_DIR}"
    fi
    
    log_success "BusyBox source ready"
}

#-------------------------------------------------------------------------------
# Build Functions
#-------------------------------------------------------------------------------

build_uboot() {
    log_info "Building U-Boot for ${TARGET}..."
    
    local arch="${TARGET_ARCH[$TARGET]}"
    local cross="${TARGET_CROSS_COMPILE[$TARGET]}"
    local defconfig="${UBOOT_DEFCONFIG[$TARGET]}"
    
    cd "${UBOOT_DIR}"
    
    # Clean previous build
    make distclean
    
    # Configure
    log_info "Configuring U-Boot with ${defconfig}..."
    make ARCH="${arch}" CROSS_COMPILE="${cross}" "${defconfig}"
    
    # Build
    log_info "Compiling U-Boot (using ${JOBS} jobs)..."
    make ARCH="${arch}" CROSS_COMPILE="${cross}" -j"${JOBS}"
    
    # Copy output files
    log_info "Copying U-Boot binaries..."
    cp -v u-boot.bin "${OUTPUT_DIR}/${TARGET}/boot/"
    
    # Copy SPL if it exists (for platforms that use it)
    if [ -f "SPL" ]; then
        cp -v SPL "${OUTPUT_DIR}/${TARGET}/boot/"
    fi
    
    if [ -f "u-boot.img" ]; then
        cp -v u-boot.img "${OUTPUT_DIR}/${TARGET}/boot/"
    fi
    
    # For Raspberry Pi, also copy u-boot.bin
    if [[ "${TARGET}" == rpi* ]]; then
        # RPi uses specific boot files
        log_info "Note: For Raspberry Pi, you also need:"
        log_info "  - bootcode.bin, start.elf, fixup.dat from Raspberry Pi firmware"
        log_info "  - config.txt with: kernel=u-boot.bin"
    fi
    
    log_success "U-Boot build complete"
}

build_kernel() {
    log_info "Building Linux kernel for ${TARGET}..."
    
    local arch="${TARGET_ARCH[$TARGET]}"
    local cross="${TARGET_CROSS_COMPILE[$TARGET]}"
    local defconfig="${KERNEL_DEFCONFIG[$TARGET]}"
    local image="${KERNEL_IMAGE[$TARGET]}"
    
    cd "${KERNEL_DIR}"
    
    # Clean previous build
    make distclean
    
    # Configure
    log_info "Configuring kernel with ${defconfig}..."
    make ARCH="${arch}" CROSS_COMPILE="${cross}" "${defconfig}"
    
    # Build kernel image
    log_info "Compiling kernel ${image} (using ${JOBS} jobs)..."
    make ARCH="${arch}" CROSS_COMPILE="${cross}" "${image}" -j"${JOBS}"
    
    # Build device tree blobs
    log_info "Building device tree blobs..."
    make ARCH="${arch}" CROSS_COMPILE="${cross}" dtbs -j"${JOBS}"
    
    # Build modules
    log_info "Building kernel modules..."
    make ARCH="${arch}" CROSS_COMPILE="${cross}" modules -j"${JOBS}"
    
    # Copy output files
    log_info "Copying kernel image..."
    if [ "${arch}" = "arm64" ]; then
        cp -v "arch/${arch}/boot/${image}" "${OUTPUT_DIR}/${TARGET}/boot/"
    else
        cp -v "arch/${arch}/boot/${image}" "${OUTPUT_DIR}/${TARGET}/boot/"
    fi
    
    # Copy device tree blobs
    log_info "Copying device tree blobs..."
    mkdir -p "${OUTPUT_DIR}/${TARGET}/boot/dtbs"
    find "arch/${arch}/boot/dts" -name "*.dtb" -exec cp -v {} "${OUTPUT_DIR}/${TARGET}/boot/dtbs/" \;
    
    # Install modules
    log_info "Installing kernel modules..."
    make ARCH="${arch}" CROSS_COMPILE="${cross}" \
        INSTALL_MOD_PATH="${OUTPUT_DIR}/${TARGET}/rootfs" \
        modules_install
    
    log_success "Kernel build complete"
}

build_initramfs() {
    log_info "Building initramfs..."
    
    # Use the create_initramfs.sh script
    if [ -x "${SCRIPT_DIR}/05_initramfs/create_initramfs.sh" ]; then
        cd "${SCRIPT_DIR}/05_initramfs"
        
        # Set environment for the script
        export ARCH="${TARGET_ARCH[$TARGET]}"
        export CROSS_COMPILE="${TARGET_CROSS_COMPILE[$TARGET]}"
        export OUTPUT_DIR="${OUTPUT_DIR}/${TARGET}"
        
        ./create_initramfs.sh
        
        log_success "Initramfs build complete"
    else
        log_warn "create_initramfs.sh not found or not executable"
        log_info "Skipping initramfs build"
    fi
}

#-------------------------------------------------------------------------------
# Summary Function
#-------------------------------------------------------------------------------

print_summary() {
    echo ""
    echo "==============================================================================="
    echo "  Build Summary for ${TARGET}"
    echo "==============================================================================="
    echo ""
    echo "Output directory: ${OUTPUT_DIR}/${TARGET}/"
    echo ""
    echo "Generated files:"
    echo ""
    
    if [ -d "${OUTPUT_DIR}/${TARGET}" ]; then
        find "${OUTPUT_DIR}/${TARGET}" -type f -exec ls -lh {} \;
    fi
    
    echo ""
    echo "-------------------------------------------------------------------------------"
    echo "Next Steps:"
    echo "-------------------------------------------------------------------------------"
    echo ""
    echo "1. Format an SD card with two partitions:"
    echo "   - Partition 1: FAT32, ~100MB, labeled 'boot'"
    echo "   - Partition 2: ext4, remaining space, labeled 'rootfs'"
    echo ""
    echo "2. Copy boot files to the boot partition:"
    echo "   cp ${OUTPUT_DIR}/${TARGET}/boot/* /media/\$USER/boot/"
    echo ""
    echo "3. Extract rootfs to the rootfs partition:"
    echo "   sudo cp -a ${OUTPUT_DIR}/${TARGET}/rootfs/* /media/\$USER/rootfs/"
    echo ""
    echo "4. Insert SD card into ${TARGET} and boot!"
    echo ""
    echo "For detailed instructions, see the lab READMEs."
    echo ""
    echo "==============================================================================="
}

#-------------------------------------------------------------------------------
# Main Entry Point
#-------------------------------------------------------------------------------

main() {
    print_banner
    
    # Check for target argument
    if [ $# -lt 1 ]; then
        print_usage
        exit 1
    fi
    
    TARGET="$1"
    
    # Validate target
    if [ -z "${TARGET_ARCH[$TARGET]+x}" ]; then
        log_error "Unknown target: ${TARGET}"
        print_usage
        exit 1
    fi
    
    log_info "Building for target: ${TARGET}"
    log_info "Architecture: ${TARGET_ARCH[$TARGET]}"
    log_info "Cross-compiler: ${TARGET_CROSS_COMPILE[$TARGET]}"
    echo ""
    
    # Export environment variables for sub-scripts
    export ARCH="${TARGET_ARCH[$TARGET]}"
    export CROSS_COMPILE="${TARGET_CROSS_COMPILE[$TARGET]}"
    export TARGET
    
    # Run build steps
    check_dependencies
    create_directories
    
    echo ""
    log_info "Step 1/4: Fetching sources..."
    echo "-------------------------------------------------------------------------------"
    fetch_uboot
    fetch_kernel
    fetch_busybox
    
    echo ""
    log_info "Step 2/4: Building U-Boot..."
    echo "-------------------------------------------------------------------------------"
    build_uboot
    
    echo ""
    log_info "Step 3/4: Building Linux kernel..."
    echo "-------------------------------------------------------------------------------"
    build_kernel
    
    echo ""
    log_info "Step 4/4: Building initramfs..."
    echo "-------------------------------------------------------------------------------"
    build_initramfs
    
    # Print summary
    print_summary
    
    log_success "All builds completed successfully!"
}

# Run main function with all arguments
main "$@"
