#!/bin/bash
#
# create_recipe.sh - Create a new Yocto recipe
#
# Usage:
#   ./create_recipe.sh <recipe_name> [type]
#
# Author: Embedded Linux Labs
# License: MIT

set -e

RECIPE_NAME="${1:-}"
RECIPE_TYPE="${2:-app}"
YOCTO_DIR="${YOCTO_DIR:-$HOME/yocto-bbb/poky}"
LAYER_DIR="$YOCTO_DIR/meta-bbb-custom"
VERSION="1.0"

# Terminal colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

show_usage() {
    cat << EOF
Usage: $0 <recipe_name> [type]

Create a new Yocto recipe in meta-bbb-custom layer.

Arguments:
    recipe_name   Name for the new recipe (required)
    type          Recipe type (default: app)
                    app     - Application recipe
                    service - Systemd service recipe
                    module  - Kernel module recipe
                    config  - Configuration-only recipe

Example:
    $0 myapp app
    $0 myservice service
    $0 mydriver module
EOF
}

check_layer() {
    if [ ! -d "$LAYER_DIR" ]; then
        log_error "Custom layer not found: $LAYER_DIR"
        echo "Run setup_yocto.sh first"
        exit 1
    fi
}

create_app_recipe() {
    local recipe_dir="$LAYER_DIR/recipes-app/$RECIPE_NAME"
    mkdir -p "$recipe_dir/files"
    
    # Main recipe
    cat > "$recipe_dir/${RECIPE_NAME}_${VERSION}.bb" << EOF
SUMMARY = "${RECIPE_NAME} application"
DESCRIPTION = "Custom application for BeagleBone Black"
HOMEPAGE = "https://example.com/${RECIPE_NAME}"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://\${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

# Source files
SRC_URI = "file://${RECIPE_NAME}.c \\
           file://Makefile"

# Source directory
S = "\${WORKDIR}"

# Dependencies (uncomment as needed)
# DEPENDS = "libgpiod"
# RDEPENDS:\${PN} = "libgpiod"

# Compilation
do_compile() {
    oe_runmake
}

# Installation
do_install() {
    install -d \${D}\${bindir}
    install -m 0755 ${RECIPE_NAME} \${D}\${bindir}
}

# Package files
FILES:\${PN} = "\${bindir}/${RECIPE_NAME}"
EOF
    
    # Source file
    cat > "$recipe_dir/files/${RECIPE_NAME}.c" << EOF
/*
 * ${RECIPE_NAME}.c - Custom BeagleBone Black Application
 *
 * Generated by create_recipe.sh
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#define VERSION "${VERSION}"

void print_help(const char *prog) {
    printf("Usage: %s [options]\\n", prog);
    printf("\\nOptions:\\n");
    printf("  -h    Show this help\\n");
    printf("  -v    Show version\\n");
}

int main(int argc, char *argv[]) {
    int opt;
    
    while ((opt = getopt(argc, argv, "hv")) != -1) {
        switch (opt) {
            case 'v':
                printf("${RECIPE_NAME} version %s\\n", VERSION);
                return 0;
            case 'h':
            default:
                print_help(argv[0]);
                return 0;
        }
    }
    
    printf("Hello from ${RECIPE_NAME}!\\n");
    printf("Running on BeagleBone Black\\n");
    
    return 0;
}
EOF
    
    # Makefile
    cat > "$recipe_dir/files/Makefile" << EOF
CC ?= gcc
CFLAGS ?= -Wall -O2
LDFLAGS ?=

TARGET = ${RECIPE_NAME}
SRCS = ${RECIPE_NAME}.c
OBJS = \$(SRCS:.c=.o)

all: \$(TARGET)

\$(TARGET): \$(OBJS)
	\$(CC) \$(LDFLAGS) -o \$@ \$^

%.o: %.c
	\$(CC) \$(CFLAGS) -c -o \$@ \$<

clean:
	rm -f \$(TARGET) \$(OBJS)

.PHONY: all clean
EOF
    
    log_info "Created application recipe: $recipe_dir"
}

create_service_recipe() {
    local recipe_dir="$LAYER_DIR/recipes-app/$RECIPE_NAME"
    mkdir -p "$recipe_dir/files"
    
    # Main recipe
    cat > "$recipe_dir/${RECIPE_NAME}_${VERSION}.bb" << EOF
SUMMARY = "${RECIPE_NAME} systemd service"
DESCRIPTION = "Systemd service for BeagleBone Black"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://\${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

inherit systemd

SRC_URI = "file://${RECIPE_NAME}.sh \\
           file://${RECIPE_NAME}.service"

S = "\${WORKDIR}"

# Enable service by default
SYSTEMD_SERVICE:\${PN} = "${RECIPE_NAME}.service"
SYSTEMD_AUTO_ENABLE = "enable"

do_install() {
    # Install script
    install -d \${D}\${bindir}
    install -m 0755 ${RECIPE_NAME}.sh \${D}\${bindir}/${RECIPE_NAME}
    
    # Install systemd service
    install -d \${D}\${systemd_system_unitdir}
    install -m 0644 ${RECIPE_NAME}.service \${D}\${systemd_system_unitdir}
}

FILES:\${PN} = "\${bindir}/${RECIPE_NAME} \\
               \${systemd_system_unitdir}/${RECIPE_NAME}.service"
EOF
    
    # Service script
    cat > "$recipe_dir/files/${RECIPE_NAME}.sh" << EOF
#!/bin/sh
#
# ${RECIPE_NAME} service script
#

LOG_FILE=/var/log/${RECIPE_NAME}.log

log() {
    echo "\$(date): \$1" >> \$LOG_FILE
}

case "\$1" in
    start)
        log "Service starting..."
        while true; do
            log "Service running..."
            sleep 60
        done
        ;;
    stop)
        log "Service stopping..."
        ;;
    *)
        echo "Usage: \$0 {start|stop}"
        exit 1
        ;;
esac
EOF
    
    # Systemd unit file
    cat > "$recipe_dir/files/${RECIPE_NAME}.service" << EOF
[Unit]
Description=${RECIPE_NAME} Service
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/${RECIPE_NAME} start
ExecStop=/usr/bin/${RECIPE_NAME} stop
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
    
    log_info "Created service recipe: $recipe_dir"
}

create_module_recipe() {
    local recipe_dir="$LAYER_DIR/recipes-kernel/${RECIPE_NAME}"
    mkdir -p "$recipe_dir/files"
    
    # Main recipe
    cat > "$recipe_dir/${RECIPE_NAME}_${VERSION}.bb" << EOF
SUMMARY = "${RECIPE_NAME} kernel module"
DESCRIPTION = "Custom kernel module for BeagleBone Black"
LICENSE = "GPL-2.0-only"
LIC_FILES_CHKSUM = "file://\${COMMON_LICENSE_DIR}/GPL-2.0-only;md5=801f80980d171dd6425610833a22dbe6"

inherit module

SRC_URI = "file://Makefile \\
           file://${RECIPE_NAME}.c"

S = "\${WORKDIR}"

# The inherit module handles everything for kernel modules
EOF
    
    # Module source
    cat > "$recipe_dir/files/${RECIPE_NAME}.c" << EOF
/*
 * ${RECIPE_NAME}.c - Custom kernel module for BeagleBone Black
 *
 * Generated by create_recipe.sh
 */

#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/init.h>

MODULE_LICENSE("GPL");
MODULE_AUTHOR("Embedded Linux Labs");
MODULE_DESCRIPTION("${RECIPE_NAME} kernel module");
MODULE_VERSION("${VERSION}");

static int __init ${RECIPE_NAME}_init(void)
{
    pr_info("${RECIPE_NAME}: Module loaded\\n");
    return 0;
}

static void __exit ${RECIPE_NAME}_exit(void)
{
    pr_info("${RECIPE_NAME}: Module unloaded\\n");
}

module_init(${RECIPE_NAME}_init);
module_exit(${RECIPE_NAME}_exit);
EOF
    
    # Makefile
    cat > "$recipe_dir/files/Makefile" << EOF
obj-m := ${RECIPE_NAME}.o

SRC := \$(shell pwd)

all:
	\$(MAKE) -C \$(KERNEL_SRC) M=\$(SRC)

modules_install:
	\$(MAKE) -C \$(KERNEL_SRC) M=\$(SRC) modules_install

clean:
	rm -f *.o *~ core .depend .*.cmd *.ko *.mod.c
	rm -f Module.markers Module.symvers modules.order
	rm -rf .tmp_versions Modules.symvers
EOF
    
    log_info "Created kernel module recipe: $recipe_dir"
}

create_config_recipe() {
    local recipe_dir="$LAYER_DIR/recipes-core/${RECIPE_NAME}"
    mkdir -p "$recipe_dir/files"
    
    # Main recipe
    cat > "$recipe_dir/${RECIPE_NAME}_${VERSION}.bb" << EOF
SUMMARY = "${RECIPE_NAME} configuration"
DESCRIPTION = "Configuration files for BeagleBone Black"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://\${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

SRC_URI = "file://${RECIPE_NAME}.conf"

S = "\${WORKDIR}"

do_install() {
    install -d \${D}\${sysconfdir}
    install -m 0644 ${RECIPE_NAME}.conf \${D}\${sysconfdir}
}

FILES:\${PN} = "\${sysconfdir}/${RECIPE_NAME}.conf"
EOF
    
    # Configuration file
    cat > "$recipe_dir/files/${RECIPE_NAME}.conf" << EOF
# ${RECIPE_NAME} configuration file
# Generated by create_recipe.sh

# Example settings
ENABLED=true
LOG_LEVEL=info
EOF
    
    log_info "Created configuration recipe: $recipe_dir"
}

# ==========================================================================
# MAIN
# ==========================================================================

if [ -z "$RECIPE_NAME" ]; then
    show_usage
    exit 1
fi

case "${RECIPE_NAME}" in
    -h|--help)
        show_usage
        exit 0
        ;;
esac

echo ""
echo "========================================"
echo " Yocto Recipe Creator"
echo "========================================"
echo ""

check_layer

case "${RECIPE_TYPE}" in
    app)
        create_app_recipe
        ;;
    service)
        create_service_recipe
        ;;
    module)
        create_module_recipe
        ;;
    config)
        create_config_recipe
        ;;
    *)
        log_error "Unknown recipe type: $RECIPE_TYPE"
        show_usage
        exit 1
        ;;
esac

echo ""
echo "To build the recipe:"
echo "  cd $YOCTO_DIR"
echo "  source oe-init-build-env build-bbb"
echo "  bitbake $RECIPE_NAME"
echo ""
echo "To add to image, edit IMAGE_INSTALL in your image recipe:"
echo "  IMAGE_INSTALL += \"$RECIPE_NAME\""
echo ""
