#!/bin/bash
#
# create_sd_card.sh - Create bootable SD card for BeagleBone Black
#
# Usage:
#   ./create_sd_card.sh /dev/sdX [images_dir]
#
# WARNING: This will DESTROY all data on the specified device!
#
# Author: Embedded Linux Labs
# License: MIT

set -e

DEVICE="$1"
IMAGES_DIR="${2:-$HOME/bbb-buildroot/buildroot-2024.02/output/images}"

# Terminal colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

show_usage() {
    cat << EOF
Usage: $0 /dev/sdX [images_dir]

Create bootable SD card for BeagleBone Black.

Arguments:
    /dev/sdX      SD card device (required)
    images_dir    Buildroot output/images directory

WARNING: All data on the device will be destroyed!

Example:
    $0 /dev/sdc
    $0 /dev/mmcblk0 ~/buildroot/output/images
EOF
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_error "This script must be run as root (sudo)"
        exit 1
    fi
}

validate_device() {
    if [ -z "$DEVICE" ]; then
        log_error "No device specified"
        show_usage
        exit 1
    fi
    
    if [ ! -b "$DEVICE" ]; then
        log_error "Device not found: $DEVICE"
        exit 1
    fi
    
    # Check if it's the system disk
    if [ "$DEVICE" = "/dev/sda" ] || [ "$DEVICE" = "/dev/nvme0n1" ]; then
        log_error "Refusing to write to system disk: $DEVICE"
        exit 1
    fi
    
    # Check if mounted
    if mount | grep -q "$DEVICE"; then
        log_error "Device is mounted. Unmount first:"
        mount | grep "$DEVICE"
        exit 1
    fi
}

check_images() {
    log_info "Checking images in: $IMAGES_DIR"
    
    local required=("MLO" "u-boot.img" "zImage" "am335x-boneblack.dtb" "rootfs.ext4")
    local missing=()
    
    for img in "${required[@]}"; do
        if [ ! -f "$IMAGES_DIR/$img" ]; then
            missing+=("$img")
        else
            log_info "  Found: $img ($(stat -c%s "$IMAGES_DIR/$img") bytes)"
        fi
    done
    
    if [ ${#missing[@]} -gt 0 ]; then
        log_error "Missing images: ${missing[*]}"
        echo "Build Buildroot first: make -j\$(nproc)"
        exit 1
    fi
}

confirm_write() {
    echo ""
    echo -e "${RED}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${RED}║  WARNING: ALL DATA ON $DEVICE WILL BE DESTROYED!  ║${NC}"
    echo -e "${RED}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Device information:"
    lsblk "$DEVICE" 2>/dev/null || true
    echo ""
    
    read -p "Type 'yes' to continue: " confirm
    if [ "$confirm" != "yes" ]; then
        log_info "Cancelled"
        exit 0
    fi
}

partition_device() {
    log_info "Partitioning device..."
    
    # Clear existing partitions
    dd if=/dev/zero of="$DEVICE" bs=1M count=10 2>/dev/null
    
    # Create partition table
    parted -s "$DEVICE" mklabel msdos
    
    # Boot partition (FAT32, 64MB)
    parted -s "$DEVICE" mkpart primary fat32 1MiB 65MiB
    parted -s "$DEVICE" set 1 boot on
    
    # Root partition (ext4, rest of card)
    parted -s "$DEVICE" mkpart primary ext4 65MiB 100%
    
    # Wait for kernel to detect partitions
    sync
    partprobe "$DEVICE" 2>/dev/null || true
    sleep 2
    
    log_info "Partitions created"
}

get_partition() {
    local device=$1
    local num=$2
    
    # Handle different naming conventions
    if [[ "$device" == *"mmcblk"* ]] || [[ "$device" == *"nvme"* ]]; then
        echo "${device}p${num}"
    else
        echo "${device}${num}"
    fi
}

format_partitions() {
    local boot_part=$(get_partition "$DEVICE" 1)
    local root_part=$(get_partition "$DEVICE" 2)
    
    log_info "Formatting partitions..."
    
    # Format boot partition
    mkfs.vfat -F 32 -n "BOOT" "$boot_part"
    
    # Format root partition
    mkfs.ext4 -L "rootfs" -F "$root_part"
    
    log_info "Formatting complete"
}

mount_partitions() {
    boot_mount=$(mktemp -d)
    root_mount=$(mktemp -d)
    
    local boot_part=$(get_partition "$DEVICE" 1)
    local root_part=$(get_partition "$DEVICE" 2)
    
    mount "$boot_part" "$boot_mount"
    mount "$root_part" "$root_mount"
    
    log_info "Mounted partitions"
}

copy_boot_files() {
    log_info "Copying boot files..."
    
    cp "$IMAGES_DIR/MLO" "$boot_mount/"
    cp "$IMAGES_DIR/u-boot.img" "$boot_mount/"
    cp "$IMAGES_DIR/zImage" "$boot_mount/"
    cp "$IMAGES_DIR/am335x-boneblack.dtb" "$boot_mount/"
    
    # Create uEnv.txt
    cat > "$boot_mount/uEnv.txt" << 'EOF'
# BeagleBone Black Boot Configuration
# Generated by create_sd_card.sh

bootpart=0:1
bootdir=
bootfile=zImage
fdtfile=am335x-boneblack.dtb

# Console settings
console=ttyO0,115200n8

# Root filesystem settings
rootpart=0:2
rootfstype=ext4

# Boot command
uenvcmd=echo Booting from SD card...; \
    fatload mmc ${bootpart} ${loadaddr} ${bootfile}; \
    fatload mmc ${bootpart} ${fdtaddr} ${fdtfile}; \
    setenv bootargs console=${console} root=/dev/mmcblk0p2 rootwait rw; \
    bootz ${loadaddr} - ${fdtaddr}
EOF
    
    log_info "Boot files copied"
    ls -la "$boot_mount/"
}

copy_rootfs() {
    log_info "Copying root filesystem..."
    
    if [ -f "$IMAGES_DIR/rootfs.tar" ]; then
        tar xf "$IMAGES_DIR/rootfs.tar" -C "$root_mount"
    elif [ -f "$IMAGES_DIR/rootfs.ext4" ]; then
        # Use dd for ext4 image
        local root_part=$(get_partition "$DEVICE" 2)
        umount "$root_mount" 2>/dev/null || true
        dd if="$IMAGES_DIR/rootfs.ext4" of="$root_part" bs=4M status=progress
        mount "$root_part" "$root_mount"
    else
        log_error "No rootfs found"
        exit 1
    fi
    
    log_info "Root filesystem copied"
}

cleanup() {
    log_info "Syncing and unmounting..."
    
    sync
    
    if [ -n "$boot_mount" ] && mountpoint -q "$boot_mount" 2>/dev/null; then
        umount "$boot_mount"
        rmdir "$boot_mount"
    fi
    
    if [ -n "$root_mount" ] && mountpoint -q "$root_mount" 2>/dev/null; then
        umount "$root_mount"
        rmdir "$root_mount"
    fi
}

print_summary() {
    echo ""
    echo "════════════════════════════════════════════════════════════"
    echo "  SD CARD READY"
    echo "════════════════════════════════════════════════════════════"
    echo ""
    echo "Device: $DEVICE"
    echo ""
    echo "Partitions:"
    lsblk "$DEVICE"
    echo ""
    echo "Boot instructions:"
    echo "  1. Insert SD card into BeagleBone Black"
    echo "  2. Hold S2 button (boot button) while powering on"
    echo "  3. Connect serial console: screen /dev/ttyACM0 115200"
    echo "  4. Login: root / root"
    echo ""
}

# ==========================================================================
# MAIN
# ==========================================================================

case "${1:-}" in
    -h|--help)
        show_usage
        exit 0
        ;;
esac

echo ""
echo "========================================"
echo " BeagleBone Black SD Card Creator"
echo "========================================"
echo ""

check_root
validate_device
check_images
confirm_write

trap cleanup EXIT

partition_device
format_partitions
mount_partitions
copy_boot_files
copy_rootfs
cleanup

print_summary
