#!/bin/bash
#
# build_kernel.sh - Build Linux kernel for embedded targets
#
# AUTO-GENERATED: This script was generated by AI. Verify before use.
#
# This script automates the Linux kernel build process for various
# embedded boards, handling configuration, compilation, and output
# organization.
#
# PRIMARY TARGET: BeagleBone Black Rev. C (AM335x)
#
# Usage: ./build_kernel.sh <target>
# Targets: bbb (primary), rpi3, rpi4, imx6
#
# Example: ./build_kernel.sh bbb
#

set -e
set -u

#==============================================================================
# Configuration
#==============================================================================

KERNEL_VERSION="${KERNEL_VERSION:-6.6}"
WORK_DIR="${WORK_DIR:-$(pwd)/kernel_build}"
OUTPUT_DIR="${OUTPUT_DIR:-$(pwd)/output}"

# Kernel source repositories
declare -A KERNEL_REPO=(
    ["bbb"]="https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git"
    ["rpi3"]="https://github.com/raspberrypi/linux"
    ["rpi4"]="https://github.com/raspberrypi/linux"
    ["imx6"]="https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git"
    ["mainline"]="https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git"
)

# Kernel branches
declare -A KERNEL_BRANCH=(
    ["bbb"]="linux-6.6.y"
    ["rpi3"]="rpi-6.6.y"
    ["rpi4"]="rpi-6.6.y"
    ["imx6"]="linux-6.6.y"
    ["mainline"]="linux-6.6.y"
)

# Default configurations
declare -A KERNEL_DEFCONFIG=(
    ["bbb"]="omap2plus_defconfig"      # TI AM335x / OMAP
    ["rpi3"]="bcm2709_defconfig"
    ["rpi4"]="bcm2711_defconfig"
    ["imx6"]="imx_v6_v7_defconfig"
    ["mainline"]="multi_v7_defconfig"
)

# Cross compilers (BBB uses ARM 32-bit)
declare -A CROSS_COMPILER=(
    ["bbb"]="arm-linux-gnueabihf-"
    ["rpi3"]="arm-linux-gnueabihf-"
    ["rpi4"]="aarch64-linux-gnu-"
    ["imx6"]="arm-linux-gnueabihf-"
    ["mainline"]="arm-linux-gnueabihf-"
)

# Device tree files
declare -A KERNEL_DTB=(
    ["bbb"]="am335x-boneblack.dtb"
    ["rpi3"]="bcm2710-rpi-3-b.dtb"
    ["rpi4"]="bcm2711-rpi-4-b.dtb"
    ["imx6"]="imx6q-sabresd.dtb"
    ["mainline"]=""
)

# Architectures
declare -A TARGET_ARCH=(
    ["rpi3"]="arm"
    ["rpi4"]="arm64"
    ["bbb"]="arm"
    ["imx6"]="arm"
    ["mainline"]="arm"
)

# Kernel image names
declare -A KERNEL_IMAGE=(
    ["rpi3"]="zImage"
    ["rpi4"]="Image"
    ["bbb"]="zImage"
    ["imx6"]="zImage"
    ["mainline"]="zImage"
)

# DTB patterns
declare -A DTB_PATTERN=(
    ["rpi3"]="arch/arm/boot/dts/broadcom/bcm2710*.dtb"
    ["rpi4"]="arch/arm64/boot/dts/broadcom/bcm2711*.dtb"
    ["bbb"]="arch/arm/boot/dts/ti/omap/am335x-bone*.dtb"
    ["imx6"]="arch/arm/boot/dts/nxp/imx/imx6*.dtb"
    ["mainline"]="arch/arm/boot/dts/*.dtb"
)

#==============================================================================
# Functions
#==============================================================================

print_usage() {
    echo "Usage: $0 <target> [options]"
    echo ""
    echo "Targets:"
    echo "  rpi3     - Raspberry Pi 3 (32-bit)"
    echo "  rpi4     - Raspberry Pi 4 (64-bit)"
    echo "  bbb      - BeagleBone Black"
    echo "  imx6     - i.MX6 boards"
    echo "  mainline - Generic multi_v7"
    echo ""
    echo "Options:"
    echo "  --menuconfig  Open menuconfig after defconfig"
    echo "  --clean       Clean before building"
    echo "  --dtbs-only   Build only device trees"
    echo "  --modules     Build modules"
    echo ""
    echo "Environment variables:"
    echo "  KERNEL_VERSION - Kernel version branch"
    echo "  WORK_DIR       - Build directory"
    echo "  OUTPUT_DIR     - Output directory"
}

log_info() {
    echo "[INFO] $1"
}

log_error() {
    echo "[ERROR] $1" >&2
}

check_dependencies() {
    log_info "Checking dependencies..."
    
    local deps=("git" "make" "gcc" "bison" "flex" "bc" "libncurses-dev")
    local missing=()
    
    for dep in git make gcc bison flex bc; do
        if ! command -v "$dep" &> /dev/null; then
            missing+=("$dep")
        fi
    done
    
    # Check cross-compiler
    local cc="${CROSS_COMPILER[$TARGET]}"
    if ! command -v "${cc}gcc" &> /dev/null; then
        log_error "Cross-compiler not found: ${cc}gcc"
        log_error "Install with appropriate package for your distribution"
        exit 1
    fi
    
    if [ ${#missing[@]} -ne 0 ]; then
        log_error "Missing: ${missing[*]}"
        exit 1
    fi
    
    log_info "Dependencies OK"
}

fetch_kernel() {
    log_info "Fetching kernel source..."
    
    mkdir -p "$WORK_DIR"
    cd "$WORK_DIR"
    
    local repo="${KERNEL_REPO[$TARGET]}"
    local branch="${KERNEL_BRANCH[$TARGET]}"
    
    if [ -d "linux" ]; then
        log_info "Kernel source exists, updating..."
        cd linux
        git fetch origin "$branch"
        git checkout "$branch"
        git pull
    else
        log_info "Cloning kernel repository..."
        git clone --depth=1 --branch "$branch" "$repo" linux
        cd linux
    fi
    
    log_info "Kernel source ready"
}

configure_kernel() {
    log_info "Configuring kernel..."
    
    cd "$WORK_DIR/linux"
    
    local arch="${TARGET_ARCH[$TARGET]}"
    local cross="${CROSS_COMPILER[$TARGET]}"
    local defconfig="${KERNEL_DEFCONFIG[$TARGET]}"
    
    export ARCH="$arch"
    export CROSS_COMPILE="$cross"
    
    log_info "Architecture: $arch"
    log_info "Cross-compiler: $cross"
    log_info "Defconfig: $defconfig"
    
    make "$defconfig"
    
    if [ "$DO_MENUCONFIG" = true ]; then
        log_info "Opening menuconfig..."
        make menuconfig
    fi
}

build_kernel() {
    log_info "Building kernel..."
    
    cd "$WORK_DIR/linux"
    
    local arch="${TARGET_ARCH[$TARGET]}"
    local cross="${CROSS_COMPILER[$TARGET]}"
    local image="${KERNEL_IMAGE[$TARGET]}"
    
    export ARCH="$arch"
    export CROSS_COMPILE="$cross"
    
    if [ "$DTBS_ONLY" = true ]; then
        log_info "Building device trees only..."
        make -j"$(nproc)" dtbs
    else
        log_info "Building kernel image..."
        make -j"$(nproc)" "$image"
        
        log_info "Building device trees..."
        make -j"$(nproc)" dtbs
        
        if [ "$BUILD_MODULES" = true ]; then
            log_info "Building modules..."
            make -j"$(nproc)" modules
        fi
    fi
    
    log_info "Build completed"
}

install_kernel() {
    log_info "Copying output files..."
    
    mkdir -p "$OUTPUT_DIR/$TARGET"
    cd "$WORK_DIR/linux"
    
    local arch="${TARGET_ARCH[$TARGET]}"
    local image="${KERNEL_IMAGE[$TARGET]}"
    local dtb_pattern="${DTB_PATTERN[$TARGET]}"
    
    # Copy kernel image
    if [ -f "arch/$arch/boot/$image" ]; then
        cp "arch/$arch/boot/$image" "$OUTPUT_DIR/$TARGET/"
        log_info "Copied: $image"
    fi
    
    # Copy device trees
    mkdir -p "$OUTPUT_DIR/$TARGET/dtbs"
    for dtb in $dtb_pattern; do
        if [ -f "$dtb" ]; then
            cp "$dtb" "$OUTPUT_DIR/$TARGET/dtbs/"
        fi
    done
    log_info "Copied device trees"
    
    # Copy overlays (Raspberry Pi)
    if [[ "$TARGET" == rpi* ]] && [ -d "arch/$arch/boot/dts/overlays" ]; then
        mkdir -p "$OUTPUT_DIR/$TARGET/overlays"
        cp arch/$arch/boot/dts/overlays/*.dtbo "$OUTPUT_DIR/$TARGET/overlays/" 2>/dev/null || true
        log_info "Copied overlays"
    fi
    
    # Install modules if built
    if [ "$BUILD_MODULES" = true ]; then
        log_info "Installing modules..."
        make INSTALL_MOD_PATH="$OUTPUT_DIR/$TARGET/modules" modules_install
    fi
    
    # Copy config
    cp .config "$OUTPUT_DIR/$TARGET/kernel_config"
    
    log_info ""
    log_info "Output files in: $OUTPUT_DIR/$TARGET/"
    ls -la "$OUTPUT_DIR/$TARGET/"
}

print_deploy_instructions() {
    echo ""
    echo "=============================================="
    echo "  Deployment Instructions for $TARGET"
    echo "=============================================="
    echo ""
    
    local image="${KERNEL_IMAGE[$TARGET]}"
    
    case "$TARGET" in
        rpi3)
            echo "For Raspberry Pi 3:"
            echo "  1. Mount boot partition: sudo mount /dev/sdX1 /mnt"
            echo "  2. Backup: sudo cp /mnt/kernel7.img /mnt/kernel7.img.bak"
            echo "  3. Copy kernel: sudo cp $OUTPUT_DIR/$TARGET/$image /mnt/kernel7.img"
            echo "  4. Copy DTBs: sudo cp $OUTPUT_DIR/$TARGET/dtbs/*.dtb /mnt/"
            echo "  5. Copy overlays: sudo cp -r $OUTPUT_DIR/$TARGET/overlays /mnt/"
            echo "  6. Unmount: sudo umount /mnt"
            ;;
        rpi4)
            echo "For Raspberry Pi 4:"
            echo "  1. Mount boot partition: sudo mount /dev/sdX1 /mnt"
            echo "  2. Backup: sudo cp /mnt/kernel8.img /mnt/kernel8.img.bak"
            echo "  3. Copy kernel: sudo cp $OUTPUT_DIR/$TARGET/$image /mnt/kernel8.img"
            echo "  4. Copy DTBs: sudo cp $OUTPUT_DIR/$TARGET/dtbs/*.dtb /mnt/"
            echo "  5. Copy overlays: sudo cp -r $OUTPUT_DIR/$TARGET/overlays /mnt/"
            echo "  6. Unmount: sudo umount /mnt"
            ;;
        bbb)
            echo "For BeagleBone Black:"
            echo "  1. Mount boot partition: sudo mount /dev/sdX1 /mnt"
            echo "  2. Copy kernel: sudo cp $OUTPUT_DIR/$TARGET/$image /mnt/"
            echo "  3. Copy DTB: sudo cp $OUTPUT_DIR/$TARGET/dtbs/am335x-boneblack.dtb /mnt/"
            echo "  4. Unmount: sudo umount /mnt"
            ;;
        *)
            echo "Copy files to boot partition:"
            echo "  Kernel: $OUTPUT_DIR/$TARGET/$image"
            echo "  DTBs: $OUTPUT_DIR/$TARGET/dtbs/"
            ;;
    esac
    
    if [ "$BUILD_MODULES" = true ]; then
        echo ""
        echo "For modules:"
        echo "  1. Mount rootfs: sudo mount /dev/sdX2 /mnt"
        echo "  2. Copy modules: sudo cp -r $OUTPUT_DIR/$TARGET/modules/lib/modules/* /mnt/lib/modules/"
        echo "  3. Run depmod: sudo chroot /mnt depmod -a"
        echo "  4. Unmount: sudo umount /mnt"
    fi
    echo ""
}

clean_build() {
    log_info "Cleaning build..."
    
    if [ -d "$WORK_DIR/linux" ]; then
        cd "$WORK_DIR/linux"
        make distclean
    fi
    
    log_info "Clean completed"
}

#==============================================================================
# Main
#==============================================================================

TARGET=""
DO_MENUCONFIG=false
DO_CLEAN=false
DTBS_ONLY=false
BUILD_MODULES=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --menuconfig)
            DO_MENUCONFIG=true
            shift
            ;;
        --clean)
            DO_CLEAN=true
            shift
            ;;
        --dtbs-only)
            DTBS_ONLY=true
            shift
            ;;
        --modules)
            BUILD_MODULES=true
            shift
            ;;
        -h|--help)
            print_usage
            exit 0
            ;;
        *)
            if [ -z "$TARGET" ]; then
                TARGET="$1"
            else
                log_error "Unknown argument: $1"
                print_usage
                exit 1
            fi
            shift
            ;;
    esac
done

if [ -z "$TARGET" ]; then
    log_error "No target specified"
    print_usage
    exit 1
fi

if [ -z "${KERNEL_DEFCONFIG[$TARGET]:-}" ]; then
    log_error "Unknown target: $TARGET"
    print_usage
    exit 1
fi

echo ""
echo "=============================================="
echo "  Linux Kernel Build Script"
echo "=============================================="
echo "  Target:       $TARGET"
echo "  Defconfig:    ${KERNEL_DEFCONFIG[$TARGET]}"
echo "  Architecture: ${TARGET_ARCH[$TARGET]}"
echo "  Cross-compiler: ${CROSS_COMPILER[$TARGET]}"
echo "  Output:       $OUTPUT_DIR/$TARGET"
echo "=============================================="
echo ""

check_dependencies

if [ "$DO_CLEAN" = true ]; then
    clean_build
fi

fetch_kernel
configure_kernel
build_kernel
install_kernel
print_deploy_instructions

log_info "Done!"
