#!/bin/bash
#
# create_fit_image.sh - Create FIT image from kernel and DTB
#
# Generates a FIT (Flattened Image Tree) for signed boot
#
# Usage:
#   ./create_fit_image.sh [kernel] [dtb] [output]
#
# Author: Embedded Linux Labs
# License: MIT

set -e

KERNEL="${1:-zImage}"
DTB="${2:-am335x-boneblack.dtb}"
OUTPUT="${3:-image.fit}"
ITS_FILE="${OUTPUT%.fit}.its"

# Load addresses for AM335x
KERNEL_LOAD_ADDR="0x82000000"
KERNEL_ENTRY_ADDR="0x82000000"
DTB_LOAD_ADDR="0x88000000"

# Terminal colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

show_usage() {
    cat << EOF
Usage: $0 [kernel] [dtb] [output]

Create FIT image from kernel and device tree.

Arguments:
    kernel    Path to zImage (default: zImage)
    dtb       Path to device tree blob (default: am335x-boneblack.dtb)
    output    Output FIT image name (default: image.fit)

Example:
    $0 ~/bbb/linux/arch/arm/boot/zImage \\
       ~/bbb/linux/arch/arm/boot/dts/am335x-boneblack.dtb \\
       image.fit
EOF
}

check_prerequisites() {
    if ! command -v mkimage &> /dev/null; then
        log_error "mkimage not found. Install u-boot-tools:"
        echo "  sudo apt install u-boot-tools"
        exit 1
    fi
    
    if [ ! -f "$KERNEL" ]; then
        log_error "Kernel not found: $KERNEL"
        exit 1
    fi
    
    if [ ! -f "$DTB" ]; then
        log_error "DTB not found: $DTB"
        exit 1
    fi
    
    log_info "Kernel: $KERNEL ($(stat -c%s "$KERNEL") bytes)"
    log_info "DTB:    $DTB ($(stat -c%s "$DTB") bytes)"
}

create_its_file() {
    log_info "Creating ITS file: $ITS_FILE"
    
    cat > "$ITS_FILE" << EOF
/*
 * FIT Image Source for BeagleBone Black
 * 
 * Generated by: create_fit_image.sh
 * Date: $(date -Iseconds)
 * 
 * Contains:
 *   - Linux kernel (zImage)
 *   - Device tree blob
 *   - Signature placeholders for secure boot
 */

/dts-v1/;

/ {
    description = "Signed kernel image for BeagleBone Black";
    #address-cells = <1>;

    images {
        kernel-1 {
            description = "Linux kernel for AM335x";
            data = /incbin/("$KERNEL");
            type = "kernel";
            arch = "arm";
            os = "linux";
            compression = "none";
            load = <$KERNEL_LOAD_ADDR>;
            entry = <$KERNEL_ENTRY_ADDR>;
            
            hash-1 {
                algo = "sha256";
            };
            
            signature-1 {
                algo = "sha256,rsa2048";
                key-name-hint = "dev_key";
            };
        };

        fdt-1 {
            description = "BeagleBone Black Device Tree";
            data = /incbin/("$DTB");
            type = "flat_dt";
            arch = "arm";
            compression = "none";
            load = <$DTB_LOAD_ADDR>;
            
            hash-1 {
                algo = "sha256";
            };
            
            signature-1 {
                algo = "sha256,rsa2048";
                key-name-hint = "dev_key";
            };
        };
    };

    configurations {
        default = "conf-1";

        conf-1 {
            description = "BeagleBone Black - Secure Boot Configuration";
            kernel = "kernel-1";
            fdt = "fdt-1";
            
            signature-1 {
                algo = "sha256,rsa2048";
                key-name-hint = "dev_key";
                sign-images = "kernel", "fdt";
            };
        };
    };
};
EOF
}

create_fit_image() {
    log_info "Creating FIT image: $OUTPUT"
    
    mkimage -f "$ITS_FILE" "$OUTPUT"
    
    log_info "FIT image created successfully"
}

verify_fit_image() {
    log_info "Verifying FIT image..."
    echo ""
    mkimage -l "$OUTPUT"
    echo ""
}

print_summary() {
    echo ""
    echo "════════════════════════════════════════════════════════════"
    echo "  FIT IMAGE CREATED"
    echo "════════════════════════════════════════════════════════════"
    echo ""
    echo "Output files:"
    ls -la "$ITS_FILE" "$OUTPUT"
    echo ""
    echo "Next steps:"
    echo "  1. Sign the image: ./sign_image.sh $OUTPUT"
    echo "  2. Or unsigned test: copy $OUTPUT to SD card boot partition"
    echo ""
    echo "U-Boot commands:"
    echo "  fatload mmc 0:1 \${loadaddr} ${OUTPUT##*/}"
    echo "  bootm \${loadaddr}"
    echo ""
}

# ==========================================================================
# MAIN
# ==========================================================================

case "${1:-}" in
    -h|--help)
        show_usage
        exit 0
        ;;
esac

echo ""
echo "========================================"
echo " FIT Image Creator"
echo "========================================"
echo ""

check_prerequisites
create_its_file
create_fit_image
verify_fit_image
print_summary
